# Generated by Django 5.1.2 on 2024-11-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_marks_delete_studentmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marks',
            new_name='StudentMarks',
        ),
    ]
